version: "3.3"

services:

  # Traefik service (container)
  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"
    # Commands listed below determine configuration of our traefik instance
    command:
      - "--api.insecure=true" # Enables traefik dashboard that will listen on port 8080
      - "--providers.docker=true" # Defines docker as a provider
      - "--providers.docker.exposedbydefault=false" # Prevents from exposing all containers by default
      - "--entrypoints.web.address=:80" # Will listen to incoming requests on port 80
    
    # Here we map ports from container to our host machine
    # which means that port 80 on our machine will access port 80 in traefik service
    ports:
      - "80:80"
      - "8080:8080"
    
    # Here we will share docker.sock file that is present in our host machine
    # with this container. It will allow Traefik to listen to Docker events
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  frontend: 
    image: traefik/whoami
    command: -name frontend
    labels:
      - "traefik.enable=true" 
      - "traefik.http.routers.frontend.rule=Host(`app.localhost`)"

  backend:
   image: traefik/whoami
   command: -name backend
   labels: 
    - "traefik.enable=true"
    - "traefik.http.routers.backend.rule=Host(`app.localhost`) && PathPrefix(`/api`)"

  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
